// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package at.ac.uibk.qe.sowe;

import at.ac.uibk.qe.sowe.SocialElement;

privileged aspect SocialElement_Roo_JavaBean {
    
    public String SocialElement.getContent() {
        return this.content;
    }
    
    public void SocialElement.setContent(String content) {
        this.content = content;
    }
    
}
