// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package at.ac.uibk.qe.sowe;

import at.ac.uibk.qe.sowe.AnchorDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AnchorDataOnDemand_Roo_Configurable {
    
    declare @type: AnchorDataOnDemand: @Configurable;
    
}
